# -*- mode: ruby -*-
# vi: set ft=ruby :

# Case-sensitive volume in host for building Android AOSP
HOST_BUILD_VOLUME = "/Volumes/AndroidBuild"
# HOST_BUILD_VOLUME = "/Volumes/Build01"
# HOST_BUILD_VOLUME = "/Volumes/Build02"

# This is the mount point for the sync_folders in the VM
SRCMOUNT = "/opt/src"
LOCALDEV = "/local-dev"
BLDMOUNT = "/build"

CWD = File.dirname(File.expand_path(__FILE__))

TEMP_DISK="/Volumes/AndroidBuild/temp-disk.vdi"

# -----------------------------------------------------------------------------
# Vagrant definition
# -----------------------------------------------------------------------------
Vagrant.require_version ">= 1.7.4"
Vagrant.configure("2") do |config|

  # disable rsyncing folders
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # common settings: ssh login
  #config.ssh.username = "vagrant"
  #config.ssh.forward_agent = true

  # -----------------------------------
  # 1. VM for itop
  # -----------------------------------
  config.vm.define "andev" do |andev|
    andev.vm.box = "ubuntu/xenial64"
    
    # shared folders
    andev.vm.synced_folder ENV.fetch('LOCALDEVDIR', "../.."), "#{LOCALDEV}"
    andev.vm.synced_folder "..", "#{SRCMOUNT}"
    andev.vm.synced_folder "#{HOST_BUILD_VOLUME}", "#{BLDMOUNT}"

    # provisioning
    andev.vm.provision "shell", inline: <<-SCRIPT
      set -x
      # timezone
      export TZ=Asia/Shanghai
    
      # setup scripts
      cd #{LOCALDEV}/scripts/ubuntu16
      ./setup_box.sh
      # ./setup_docker-ce.sh 10.0.2.2:5000
      # ./setup_docker-compose.sh
      ./setup_aarch64-devel.sh
      # apt install -y cifs-utils samba-common system-config-samba samba winbind
    SCRIPT

    # VirtualBox
    andev.vm.hostname = "andev"
    #andev.vm.network "public_network", nic_type: "virtio", bridge: ""
    andev.vm.network "forwarded_port", guest: 20022, host: 20022
    andev.vm.network "forwarded_port", guest: 5904,  host: 5904
    # -- android adb server -- 
    andev.vm.network "forwarded_port", guest: 5037,  host: 5037
    # -- web-ui --
    andev.vm.network "forwarded_port", guest: 8080,  host: 28080

    andev.vm.provider "virtualbox" do |vb|
      vb.name = "machine-andev"
      vb.cpus = 4
      vb.memory = 8192
      vb.default_nic_type = "virtio"
      vb.customize ['modifyvm', :id, '--description', 'VM for android-arm64 devel']
      vb.customize ['modifyvm', :id, '--nictype1', 'virtio']

      # Add a second disk for temporay output and data
      unless File.exist?(TEMP_DISK)
        vb.customize ['createhd', '--filename', TEMP_DISK, '--size', 200 * 1024]
        # Adding a SATA controller that allows 2 hard drives
        # vb.customize ["storagectl", :id, "--name", "SATA",
        #  "--add", "sata", "--portcount", 1, "--hostiocache", "on", 
        #  "--bootable", "off"]
      end
      vb.customize ['storageattach', :id, '--storagectl', 'SCSI',
        '--port', 2, '--device', 0, '--type', 'hdd', '--medium', TEMP_DISK]
    end
  end

end
